#####
#
# Basic I/O System (CONFIG_PCM_SYS21X_BIOS)
#
ifeq ($(CONFIG_PCM_SYS21X_BIOS),y)

OSYS_CPM22_BIOS_BIN := $(S)dumps/pcmbios$(IMG_SFX_BIN)

endif	# CONFIG_PCM_SYS21X_BIOS

#####
#
# System Visual Debugger (CONFIG_PCM_SYS21X_SVDB)
#
ifeq ($(CONFIG_PCM_SYS21X_SVDB),y)

PCM_SYS21X_SVDB_BIN := $(S)dumps/pcmsvdb$(IMG_SFX_BIN)

endif	# CONFIG_PCM_SYS21X_SVDB

#####
#
# Voice Tape Monitor (CONFIG_PCM_SYS21X_VTAPE)
#
ifeq ($(CONFIG_PCM_SYS21X_VTAPE),y)

PCM_SYS21X_VTAPE_BIN := $(S)dumps/pcmvtape$(IMG_SFX_BIN)

endif	# CONFIG_PCM_SYS21X_VTAPE

# Local variables:
# coding: utf-8
# mode: text
# mode: make
# End:
# vim: fileencoding=utf-8 filetype=make :
