#####
#
# PC/M System Version 2.1x
#
ifeq ($(CONFIG_MACH_PCM_SYS21X),y)
$(call bi,set,mach,video,"64/16 original")
MACH_VIDEO_FONT_BIN := $(S)dumps/orig6416$(IMG_SFX_BIN)
endif

# Local variables:
# coding: utf-8
# mode: text
# mode: make
# End:
# vim: fileencoding=utf-8 filetype=make :
