#####
#
# Build Information
#
$(call bi,set,osys,name,"CP/V")

ifeq ($(CONFIG_CPV_198810),y)
include $(S)1988-10/Makefile
endif

# Local variables:
# coding: utf-8
# mode: text
# mode: make
# End:
# vim: fileencoding=utf-8 filetype=make :
