# -*- coding: utf-8 -*-
#
# kcsystems documentation build configuration file, created by
# sphinx-quickstart on Tue Oct  7 11:43:41 2014.
#
# The configuration directory must contain a file named conf.py.
# This file (containing Python code) is execfile()d with the
# current directory set to its containing dir and is called the
# "build configuration file" and contains (almost) all configuration
# needed to customize Sphinx input and output behavior.
#
# An optional file docutils.conf can be added to the configuration
# directory to adjust Docutils configuration if not otherwise overridden
# or set by Sphinx.
#
# http://www.sphinx-doc.org/en/3.x/config
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sphinx
import sys
import os

if "KCS_DOCS" not in os.environ:
    KCS_DOCS = os.path.abspath(os.getcwd())
else:
    KCS_DOCS = os.path.abspath(os.environ["KCS_DOCS"])

# if "KCS_BUILD" not in os.environ:
#     KCS_BUILD = os.path.abspath(os.path.join(KCS_DOCS, '_build'))
# else:
#     KCS_BUILD = os.path.abspath(os.environ["KCS_BUILD"])

# if "KCS_BASE" not in os.environ:
#     KCS_BASE = os.path.abspath(os.path.join(KCS_DOCS, '..'))
# else:
#     KCS_BASE = os.path.abspath(os.environ["KCS_BASE"])

# Add the 'extensions' directory to sys.path, to enable finding Sphinx
# extensions within.
sys.path.insert(0, os.path.join(KCS_DOCS, '_extensions'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_sphinx
#
needs_sphinx = '3.2.1'
build_sphinx = sphinx.__version__

# This value can be a dictionary specifying version requirements for
# extensions in 'extensions'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_extensions
#
needs_extensions = {
#   'sphinx.ext.autodoc':                       needs_sphinx,
#   'sphinx.ext.autosummary':                   needs_sphinx,
#   'sphinx.ext.autosgen':                      needs_sphinx,
    'sphinx.ext.autosectionlabel':              needs_sphinx,
    'sphinx.ext.doctest':                       needs_sphinx,
    'sphinx.ext.coverage':                      needs_sphinx,
    'sphinx.ext.todo':                          needs_sphinx,
    'sphinx.ext.ifconfig':                      needs_sphinx,
    'sphinx.ext.intersphinx':                   needs_sphinx,
#   'sphinx.ext.imgmath':                       needs_sphinx,
    'sphinx.ext.mathjax':                       needs_sphinx,
#   'sphinx.ext.jsmath':                        needs_sphinx,
#   'sphinx.ext.graphviz':                      needs_sphinx,
#   'sphinx.ext.inheritance_diagram':           needs_sphinx,
    'sphinx.ext.extlinks':                      needs_sphinx,
#   'sphinx.ext.viewcode':                      needs_sphinx,
#   'sphinx.ext.linkcode':                      needs_sphinx,
#   'matplotlib.sphinxext.mathmpl':             '3.3.1',
#   'matplotlib.sphinxext.plot_directive':      '3.3.1',
#   'sphinxcontrib.email':                      '0.2.dev20200419',
#   'sphinxcontrib.bibtex':                     '1.0.0',
    'sphinxcontrib.blockdiag':                  '2.0.0',
    'sphinxcontrib.seqdiag':                    '2.0.0',
    'sphinxcontrib.actdiag':                    '2.0.0',
    'sphinxcontrib.nwdiag':                     '2.0.0',
    'sphinxcontrib.rackdiag':                   '2.0.0',
    'sphinxcontrib.packetdiag':                 '2.0.0',
#   'sphinxcontrib.inlinesyntaxhighlight':      '0.2',
#   'sphinxcontrib.programoutput':              '0.16',
#   'sphinxcontrib.spelling':                   '5.3.0',
    'sphinxcontrib.tikz':                       '0.4.9',
#   'sphinx_tabs.tabs':                         '1.2.1',
#   'sphinx_panels':                            '0.4.1',
#   'linuxdoc.rstFlatTable':                    '20200812',
}

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-extensions
#
extensions = [
#   'sphinx.ext.autodoc',
#   'sphinx.ext.autosummary',
#   'sphinx.ext.autosgen',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
#   'sphinx.ext.imgmath',
    'sphinx.ext.mathjax',
#   'sphinx.ext.jsmath',
#   'sphinx.ext.graphviz',
#   'sphinx.ext.inheritance_diagram',
    'sphinx.ext.extlinks',
#   'sphinx.ext.viewcode',
#   'sphinx.ext.linkcode',
    'matplotlib.sphinxext.mathmpl',
    'matplotlib.sphinxext.plot_directive',
    # w/o maintenance since 2017: 'sphinxcontrib.ansi',
    'sphinxcontrib.email',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.blockdiag',
    'sphinxcontrib.seqdiag',
    'sphinxcontrib.actdiag',
    'sphinxcontrib.nwdiag',
    'sphinxcontrib.rackdiag',
    'sphinxcontrib.packetdiag',
    # w/o maintenance since 2013: 'sphinxcontrib.inlinesyntaxhighlight',
    'sphinxcontrib.programoutput',
    'sphinxcontrib.spelling',
    'sphinxcontrib.tikz',
    'linuxdoc.rstFlatTable',
    'sphinx_tabs.tabs',
    # not yet, see below "Specific configuration": 'sphinx_panels',
    'kcsystems.ultimate_replacements',
    'kcsystems.html_redirects',
    'kcsystems',
]

# -- Specific configuration -----------------------------------------------

# Only use SVG converter when it is really needed, e.g. LaTeX.
if tags.has("svgconvert"):  # pylint: disable=undefined-variable
    extensions.append('sphinxcontrib.rsvgconverter')
                   # ('sphinxcontrib.inkscapeconverter')

# Only use the Sphinx panel extension when it is really applicable, quite new.
# There are some cross side effects with the Sphinx tabs extension.
# tags.add("sphinx_panels")  # pylint: disable=undefined-variable
# tags.add("sphinx_panels_no_boostrap_css")  # pylint: disable=undefined-variable
if tags.has("sphinx_panels"):  # pylint: disable=undefined-variable
    extensions.append('sphinx_panels')
    if tags.has("sphinx_panels_no_boostrap_css"):  # pylint: disable=undefined-variable
        panels_add_boostrap_css = False  # default is: True
else:
    # use the locally mocked extension instead
    extensions.append('kcsystems.mock_sphinx_panels')

# -- Sphinx Extension Configuration ---------------------------------------

# -- sphinx.ext.autosectionlabel -- Allow reference sections using its title
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html
#

# Internally, this extension generates the labels for each section. If same
# section names are used in whole of document, any one is used for a target
# by default. The autosectionlabel_prefix_document configuration variable
# can be used to make headings which appear multiple times but in different
# documents unique.

# True to prefix each section label with the name of the document it is in,
# followed by a colon. For example, index:Introduction for a section called
# Introduction that appears in document index.rst. Useful for avoiding
# ambiguity when the same section heading appears in different documents.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html#confval-autosectionlabel_prefix_document
#
autosectionlabel_prefix_document = True


# -- sphinx.ext.doctest -- Test snippets in the
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/doctest.html
#


# -- sphinx.ext.coverage -- Collect doc coverage stats
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/coverage.html
#


# -- sphinx.ext.todo -- Support for todo items
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html
#

# If this is True, todo and todolist produce output, else they produce
# nothing. The default is False.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html#confval-todo_include_todos
#
todo_include_todos = True


# -- sphinx.ext.ifconfig -- Include content based on configuration
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/ifconfig.html
#


# -- sphinx.ext.intersphinx -- Link to other projects’ documentation

# This extension can generate automatic links to the documentation
# of objects in other projects. Usage is simple: whenever Sphinx
# encounters a cross-reference that has no matching target in the
# current documentation set, it looks for targets in the documentation
# sets configured in intersphinx_mapping.

# This config value contains the locations and names of other projects
# that should be linked to in this documentation.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html#confval-intersphinx_mapping
#
# Example configuration for intersphinx: refer to the Python standard library.
# on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
# if on_rtd:
#     intersphinx_mapping = {
#         'sphinx': ('/Users/rexut/checkouts/sphinx/doc/_build/html/', None),
#     }
# else:
intersphinx_mapping = {
    #
    # Standard reference to this docs, with local objects.inv
    #

    # python -m sphinx.ext.intersphinx 'docs/_build/html/objects.inv'
    # '': ('{}/html/'.format(KCS_BUILD), None),

    #
    # Standard reference to web docs, with web objects.inv
    #

    # python -m sphinx.ext.intersphinx 'https://docs.python.org/3/objects.inv'
    'pydocs': ('https://docs.python.org/3/', None),

    # python -m sphinx.ext.intersphinx 'https://devguide.python.org/objects.inv'
    'pydevguide': ('https://devguide.python.org/', None),

    # python -m sphinx.ext.intersphinx 'https://www.sphinx-doc.org/en/3.x/objects.inv'
    'sphinx': ('https://www.sphinx-doc.org/en/3.x/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-spelling.readthedocs.io/en/stable/objects.inv'
    'scspelling': ('https://sphinxcontrib-spelling.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-bibtex.readthedocs.io/en/stable/objects.inv'
    'scbibtex': ('https://sphinxcontrib-bibtex.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://return42.github.io/linuxdoc/objects.inv'
    'lxdoc': ('https://return42.github.io/linuxdoc/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-programoutput.readthedocs.io/en/stable/objects.inv'
    'scprgout': ('https://sphinxcontrib-programoutput.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-tikz.readthedocs.io/en/latest/objects.inv'
    'sctikz': ('https://sphinxcontrib-tikz.readthedocs.io/en/latest/', None),

    # python -m sphinx.ext.intersphinx 'http://blockdiag.com/en/objects.inv'|less
    'bldiag': ('http://blockdiag.com/en/', None),

    # python -m sphinx.ext.intersphinx 'https://matplotlib.org/objects.inv'|less
    'mplref': ('https://matplotlib.org/', None),

    # python -m sphinx.ext.intersphinx 'https://matplotlib.org/sampledoc/objects.inv'|less
    'mplsam': ('https://matplotlib.org/sampledoc/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinx-tabs.readthedocs.io/en/stable/objects.inv'
    'spxtabs': ('https://sphinx-tabs.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinx-panels.readthedocs.io/en/stable/objects.inv'
    'spxpanels': ('https://sphinx-panels.readthedocs.io/en/stable/', None),

    #
    # Drawing the Docutils objects.inv from a RTD server,
    # but referring to the 0.16 web docs
    # https://sphobjinv.readthedocs.io/en/latest/
    #

    # python -m sphinx.ext.intersphinx 'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'
    'docutils': ('https://docutils.sourceforge.io/docs/',
                 'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'),
}

# -- sphinx.ext.mathjax -- Math support for HTML outputs in Sphinx
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/math.html
#


# -- sphinx.ext.extlinks -- Markup to shorten external links
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html
#

# This extension is meant to help with the common pattern of having many
# external links that point to URLs on one and the same site, e.g. links
# to bug trackers, version control web interfaces, or simply subpages in
# other websites. It does so by providing aliases to base URLs, so that
# you only need to give the subpage name when creating a link.

# This config value must be a dictionary of external sites, mapping unique
# short alias names to a base URL and a prefix.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html#confval-extlinks
#
extlinks = {
    'gh_blob':      ('https://github.com/lipro-cpm4l/kcsystems/blob/%s', ''),
    'gh_commit':    ('https://github.com/lipro-cpm4l/kcsystems/commit/%s', ''),
    'gh_issue':     ('https://github.com/lipro-cpm4l/kcsystems/issues/%s', ''),
    'lpnstore':     ('http://store.li-pro.net/index.php?dir=%s', 'Li-Pro.Net Store: '),
    'lpnsfile':     ('http://store.li-pro.net/%s', 'Li-Pro.Net Store: '),
    'dsa':          ('https://datasheet.datasheetarchive.com/%s', 'Datasheet Archive: '),
    'hehaddrhl':    ('https://www-user.tu-chemnitz.de/~heha/basteln/Konsumg%%C3%%BCter/DDR-Halbleiter/%s', 'Henrik Haftmann, GDR-Semiconductor: '),
    'hehaddrhlpfx': ('https://www-user.tu-chemnitz.de/~heha/basteln/Konsumg%%C3%%BCter/DDR-Halbleiter/#%s', 'Henrik Haftmann, GDR-Semiconductor: '),
    'rtloc':        ('https://www.robotrontechnik.de/html/standorte/%s', 'Robotron Technique, Locations: '),
    'rtstd':        ('https://www.robotrontechnik.de/html/standards/%s', 'Robotron Technique, Standards: '),
    'rtsw':         ('https://www.robotrontechnik.de/html/software/%s', 'Robotron Technique, Software: '),
    'rtcpt':        ('https://www.robotrontechnik.de/html/computer/%s', 'Robotron Technique, Computer: '),
    'rtpnt':        ('https://www.robotrontechnik.de/html/drucker/%s', 'Robotron Technique, Printer: '),
    'rtnet':        ('https://www.robotrontechnik.de/html/netzwerke/netzwerk.htm#%s', 'Robotron Technique, Networks: '),
    'rtk1520':      ('https://www.robotrontechnik.de/html/komponenten/k1520pla.htm#%s', 'Robotron Technique, K1520: '),
    'rtcon':        ('https://www.robotrontechnik.de/html/komponenten/stecker.htm#%s', 'Robotron Technique, Connectors: '),
    'rtfdd':        ('https://www.robotrontechnik.de/html/komponenten/fs.htm#%s', 'Robotron Technique, Floppy Disk Drives: '),
    'rtemr':        ('https://www.robotrontechnik.de/html/komponenten/emr.htm#%s', 'Robotron Technique, The Single-Chip Microcontroller: '),
    'rtic':         ('https://www.robotrontechnik.de/html/komponenten/ic.htm#%s', 'Robotron Technique, Integrated Circuits: '),
    'rtkbd':        ('https://www.robotrontechnik.de/html/zubehoer/tastaturen.htm#%s', 'Robotron Technique, Keyboards: '),
    'termwiki':     ('https://terminals-wiki.org/wiki/index.php/%s', 'Terminals Wiki: '),
    'tglcate':      ('https://katalog.ub.uni-weimar.de/tgl/%s', 'TGL Catalog (BHUW): '),
    'tglbarc':      ('https://www.bbr-server.de/bauarchivddr/archiv/tglarchiv/%s', 'TGL Archive (BBSR): '),
    'udbevglddrhl': ('http://www.elektron-bbs.de/elektronik/tabellen/ddr/%s.htm', 'Udo Bertholdt, Vgl. GDR-Semiconductor: '),
    'vopofetch':    ('https://hc-ddr.hucki.net/wiki/lib/exe/fetch.php/%s', 'Volker Pohlers, GDR-HC Download: '),
    'vopowiki':     ('https://hc-ddr.hucki.net/wiki/doku.php/%s', 'Volker Pohlers, GDR-HC Wiki: '),
    'pesarnet':     ('http://www.robotron-net.de/%s', 'Peter Salomon, German Robotron Net: '),
    'mcnetart':     ('https://www.mikrocontroller.net/articles/%s', 'German Mikrocontroller Net: '),
    'itkompendium': ('https://kompendium.infotip.de/%s.html', 'German IT-Kompendium: '),
    'itwinfo':      ('https://www.itwissen.info/%s.html', 'German IT-Wissen: '),
    'wikide':       ('https://de.wikipedia.org/wiki/%s', 'German Wikipedia: '),
    'wikien':       ('https://en.wikipedia.org/wiki/%s', 'English Wikipedia: '),
    'dufaq':        ('https://docutils.sourceforge.io/FAQ.html#%s', ''),
    'dutodo':       ('https://docutils.sourceforge.io/docs/dev/todo.html#%s', ''),
    'duuser':       ('https://docutils.sourceforge.io/docs/user/rst/%s.html', ''),
    'durole':       ('https://docutils.sourceforge.io/docs/ref/rst/roles.html#%s', ''),
    'dudir':        ('https://docutils.sourceforge.io/docs/ref/rst/directives.html#%s', ''),
    'duref':        ('https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#%s', ''),
    'spxpanels':    ('https://sphinx-panels.readthedocs.io/en/stable/index.html#%s', ''),
}


# -- matplotlib.sphinxext.plot_directive -- Markup to shorten external links
#
# https://matplotlib.org/api/sphinxext_plot_directive_api.html#configuration-options
#

# Base directory, to which plot:: file names are relative to. (If None or
# empty, file names are relative to the directory where the file containing
# the directive is.)
plot_basedir = '{}/_images/mplplots'.format(KCS_DOCS)

# Default value for the include-source option.
plot_include_source = True

# Whether to show a link to the source in HTML.
plot_html_show_source_link = False

# Whether to show links to the files in HTML.
plot_html_show_formats = True

# By default, the working directory will be changed to the directory of
# the example, so the code can get at its data files, if any. Also its
# path will be added to sys.path so it can import any helper modules
# sitting beside it. This configuration option can be used to specify
# a central directory (also added to sys.path) where data files and
# helper modules for all code are located.
plot_working_directory = '{}/_images/mplplots'.format(KCS_DOCS)

# Code that should be executed before each plot. If not specified or
# None it will default to a string containing:
# 'import numpy as np; from matplotlib import pyplot as plt'
plot_pre_code = None


# -- sphinxcontrib.blockdiag -- draw block diagrams
# -- sphinxcontrib.seqdiag -- draw sequence diagrams
# -- sphinxcontrib.actdiag -- draw activity diagrams
# -- sphinxcontrib.nwdiag -- draw network diagrams
# -- sphinxcontrib.rackdiag -- draw rack diagrams
# -- sphinxcontrib.packetdiag -- draw packet diagrams
#
# http://blockdiag.com/en/blockdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/seqdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/actdiag/sphinxcontrib.html#configure-sphinx
# http://blockdiag.com/en/nwdiag/sphinxcontrib.html#configure-sphinx
#

# Fontpath for blockdiag (truetype font), The default is None.
# blockdiag_fontpath = '{}/_static/fonts/DejaVuSansCondensed.ttf'.format(KCS_DOCS)
blockdiag_fontpath = os.path.abspath('/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf')
seqdiag_fontpath = blockdiag_fontpath
actdiag_fontpath = blockdiag_fontpath
nwdiag_fontpath = blockdiag_fontpath
# rackdiag_fontpath = '{}/_static/fonts/DejaVuSansMono.ttf'.format(KCS_DOCS)
rackdiag_fontpath = os.path.abspath('/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf')
packetdiag_fontpath = rackdiag_fontpath

# Fontmap for blockdiag (maps fontfamily name to truetype font).
# The default is None.
# blockdiag_fontmap = '{}/_extensions/blockdiag.fontmap'.format(KCS_DOCS)
# seqdiag_fontmap = '{}/_extensions/seqdiag.fontmap'.format(KCS_DOCS)
# actdiag_fontmap = '{}/_extensions/actdiag.fontmap'.format(KCS_DOCS)
# nwdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(KCS_DOCS)
# rackdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(KCS_DOCS)
# packetdiag_fontmap = '{}/_extensions/nwdiag.fontmap'.format(KCS_DOCS)

# If this is True, blockdiag generates images with anti-alias filter.
# The default is False.
blockdiag_antialias = True
seqdiag_antialias = blockdiag_antialias
actdiag_antialias = blockdiag_antialias
nwdiag_antialias = blockdiag_antialias
rackdiag_antialias = blockdiag_antialias
packetdiag_antialias = blockdiag_antialias

# If this is True, blockdiag generates images with transparency background.
# The default is False.
blockdiag_transparency = True
seqdiag_transparency = blockdiag_transparency
actdiag_transparency = blockdiag_transparency
nwdiag_transparency = blockdiag_transparency
rackdiag_transparency = blockdiag_transparency
packetdiag_transparency = blockdiag_transparency

# You can specify image format on converting docs to HTML; accepts 'PNG'
# or 'SVG'. The default is 'PNG'.
blockdiag_html_image_format = 'SVG'
seqdiag_html_image_format = blockdiag_html_image_format
actdiag_html_image_format = blockdiag_html_image_format
nwdiag_html_image_format = blockdiag_html_image_format
rackdiag_html_image_format = blockdiag_html_image_format
packetdiag_html_image_format = blockdiag_html_image_format

# You can specify image format on converting docs to TeX; accepts 'PNG'
# or 'PDF'. The default is 'PNG'.
blockdiag_latex_image_format = 'PDF'
seqdiag_latex_image_format = blockdiag_latex_image_format
actdiag_latex_image_format = blockdiag_latex_image_format
nwdiag_latex_image_format = blockdiag_latex_image_format
rackdiag_latex_image_format = blockdiag_latex_image_format
packetdiag_latex_image_format = blockdiag_latex_image_format

# Enable debug mode of blockdiag.
# The default is False.
# blockdiag_debug = True
# seqdiag_debug = True
# actdiag_debug = True
# nwdiag_debug = True
# rackdiag_debug = True
# packetdiag_debug = True


# -- sphinxcontrib.spelling -- Spelling Checker
#
# https://sphinxcontrib-spelling.readthedocs.io/
#

# String specifying the language, as understood by PyEnchant and enchant.
# Defaults to en_US for US English.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#input-options
#
# spelling_lang = 'en_US'

# String specifying a file containing a list of words known to be spelled
# correctly but that do not appear in the language dictionary selected
# by spelling_lang. The file should contain one word per line. Refer to
# the PyEnchant tutorial for details.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#input-options
#
# spelling_word_list_filename = 'spelling_wordlist.txt'
spelling_word_list_filename = [
    '{}/spelling_wordlist.txt'.format(KCS_DOCS),
    '{}/mach/pcm/spelling_wordlist.txt'.format(KCS_DOCS),
    '{}/osys/cpa/spelling_wordlist.txt'.format(KCS_DOCS),
    '{}/osys/cpm/spelling_wordlist.txt'.format(KCS_DOCS),
    '/usr/share/dict/american-english-huge',
    '/usr/share/dict/ngerman',
]

# Boolean controlling whether suggestions for misspelled words are printed.
# Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#output-options
#
spelling_show_suggestions = True

# Boolean controlling whether words that look like package names from PyPI
# are treated as spelled properly. When True, the current list of package
# names is downloaded at the start of the build and used to extend the list
# of known words in the dictionary. Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_ignore_pypi_package_names = False

# Boolean controlling whether words that follow the CamelCase conventions
# used for page names in wikis should be treated as spelled properly.
# Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_ignore_wiki_words = True

# Boolean controlling treatment of words that appear in all capital letters,
# or all capital letters followed by a lower case s. When True, acronyms are
# assumed to be spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_ignore_acronyms = True

# Boolean controlling whether names built in to Python should be treated as
# spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_ignore_python_builtins = True

# Boolean controlling whether words that are names of modules found on
# sys.path are treated as spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_ignore_importable_modules = True

# List of filter classes to be added to the tokenizer that produces words
# to be checked. The classes should be derived from enchant.tokenize.Filter.
# Refer to the PyEnchant tutorial for examples.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters
#
# spelling_filters = []


# -- sphinxcontrib.tikz -- draw PGF/TikZ LaTeX pictures
#
# https://sphinxcontrib-tikz.readthedocs.io/
# https://sphinxcontrib-tikz.readthedocs.io/en/latest/#configuration
#

# Choose the image processing 'suite', either 'pdf2svg', 'Netpbm',
# 'ImageMagick', or 'GhostScript' ('pdf2svg' by default):
# tikz_proc_suite = 'ImageMagick'

# Enable/disable transparent graphics. The default is True.
tikz_transparent = True

# Add some <string> to the sub process LaTeX preamble for the html build
# target. The default is None.
# tikz_latex_preamble = ''
tikz_latex_preamble = r'''
\usepackage{fontspec}
%setmainfont[Ligatures=TeX]{DejaVu Serif}
\setmainfont[Ligatures=TeX]{DejaVu Sans Condensed}
\setsansfont[Ligatures=TeX]{DejaVu Sans Condensed}
\setmonofont[Ligatures=TeX]{DejaVu Sans Mono}
\setromanfont[Ligatures=TeX]{DejaVu Sans Condensed}
%newfontfamily\myregularfont{DejaVu Serif}
\newfontfamily\myregularfont{DejaVu Sans Condensed}
%newfontfamily\mycjkfont{WenQuanYi Micro Hei}
\newfontfamily\mycjkfont{Unifont}
\usepackage[CJK]{ucharclasses}
\setTransitionsForCJK{\mycjkfont}{\myregularfont}
'''

# Add some \usetikzlibrary{<string>} to the sub process LaTeX preamble
# for the html build target. The default is None.
tikz_tikzlibraries = r'''%%
    arrows,%%
    calendar,%%
    folding,%%
    matrix,%%
    shapes'''


# -- sphinxcontrib.rsvgconverter -- SVG to PDF converter extension
#
# https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
# https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter#configuration
#

# Path to Inkscape binary. By default, this is inkscape.
# inkscape_converter_bin = inkscape

# Additional command-line arguments for Inkscape, as a list.
# By default, this is ['--export-area-drawing'].
# inkscape_converter_args = ['--export-area-drawing']

# Path to RSVG converter binary. By default, this is rsvg-convert.
# rsvg_converter_bin = rsvg-convert

# Additional command-line arguments for the RSVG converter, as a list.
# By default, this is the emtpy list [].
# rsvg_converter_args = []


# -- Sphinx Basic Configuration -------------------------------------------

# Add any paths that contain templates here, relative to this directory.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-templates_path
#
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_suffix
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_encoding
#
#source_encoding = 'utf-8-sig'

# If given, a dictionary of parser classes for different source suffices.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_parsers
#
#source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser'}

# The master toctree document.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-master_doc
#
master_doc = 'index'

# General information about the main-/sub-projects. A dictionary of tuples.
# (source start file, target base name, title, author, documentclass)
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#project-information
#
from collections import namedtuple
docpart = namedtuple('docpart', 'master tgtclass tgtname project author')
docparts = {
    'kcs': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'KC-Systems Project',
        author = u'The KC-Systems Project',
    ),
    'kcs-mach': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'KC Machines',
        author = u'The KC-Systems Project',
    ),
    'kcs-mach-pcm': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'The Mugler-/Mathes-PC (PC/M)',
        author = u'The PC/M Maintainer Team',
    ),
    'kcs-osys': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'KC Operating Systems',
        author = u'The KC-Systems Project',
    ),
    'kcs-osys-cpa': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'The Control Program by AoS of GDR (CP/A)',
        author = u'The CP/A Maintainer Team',
    ),
    'kcs-osys-cpm': docpart(
        master = master_doc,
        tgtclass = u'manual',
        tgtname = u'kcsystems',
        project = u'The Control Program by Digital Research, Inc. (CP/M)',
        author = u'The CP/M Maintainer Team',
    ),
}

# General information about the project.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#project-information
#
project = docparts['kcs'].project
author = docparts['kcs'].author
publisher = u'Li–Pro.Net'
copyright = u'2014-2020, ' + publisher + u', KC-Systems Project members and individual contributors'
keywords = u'KC-Systems,KCS,KC/S,PC/M,CP/V,CP/A,CP/M'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#project-information
#
# The short X.Y version.
version = '0.0'
# The full version, including alpha/beta/rc tags.
release = version + '-unknown' + os.popen('../tools/setlocalversion ..').read().rstrip()

# A string of reStructuredText that will be included at the beginning of every
# source file that is read.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_prolog
#
rst_prolog = u'''
.. include:: /{docs}/docroles.rsti
.. include:: /{docs}/docmeta.rsti
.. |CREDITS| replace:: :download:`CREDITS </{docs}/CREDITS>`
.. |LICENSE| replace:: :download:`LICENSE </{docs}/LICENSE>`
.. |publisher| replace:: {publisher}
.. |copyright| replace:: {copyright}
.. |project| replace:: {project}
.. |author| replace:: {author}
.. include:: /{docs}/mach/docrefs.rsti
.. |mach_project| replace:: {mach_project}
.. |mach_author| replace:: {mach_author}
.. include:: /{docs}/mach/pcm/docrefs.rsti
.. |mach_pcm_project| replace:: {mach_pcm_project}
.. |mach_pcm_author| replace:: {mach_pcm_author}
.. |PC_M1.DOC| replace:: :download:`PC_M1.DOC </{docs}/mach/pcm/PC_M1.DOC/PC_M1.DOC>`
.. |PC_M2.DOC| replace:: :download:`PC_M2.DOC </{docs}/mach/pcm/PC_M2.DOC/PC_M2.DOC>`
.. |PC_M3.DOC| replace:: :download:`PC_M3.DOC </{docs}/mach/pcm/PC_M3.DOC/PC_M3.DOC>`
.. |PC_M4.DOC| replace:: :download:`PC_M4.DOC </{docs}/mach/pcm/PC_M4.DOC/PC_M4.DOC>`
.. |PC_MBUSK.DOC| replace:: :download:`PC_MBUSK.DOC </{docs}/mach/pcm/PC_MBUSK.DOC/PC_MBUSK.DOC>`
.. |PC_MEPT.DOC| replace:: :download:`PC_MEPT.DOC </{docs}/mach/pcm/PC_MEPT.DOC/PC_MEPT.DOC>`
.. |PC_M7659.DOC| replace:: :download:`PC_M7659.DOC </{docs}/mach/pcm/PC_M7659.DOC/PC_M7659.DOC>`
.. |IFSSV24.DOC| replace:: :download:`IFSSV24.DOC </{docs}/mach/pcm/IFSSV24.DOC/IFSSV24.DOC>`
.. |INTERROR.PCM| replace:: :download:`INTERROR.PCM </{docs}/mach/pcm/INTERROR.PCM/INTERROR.PCM>`
.. |UMBA2732.PCM| replace:: :download:`UMBA2732.PCM </{docs}/mach/pcm/UMBA2732.PCM/UMBA2732.PCM>`
.. |LESEDAS.PCM| replace:: :download:`LESEDAS.PCM </{docs}/mach/pcm/LESEDAS.PCM/LESEDAS.PCM>`
.. |SYSINFO.PCM| replace:: :download:`SYSINFO.PCM </{docs}/mach/pcm/SYSINFO.PCM/SYSINFO.PCM>`
.. |BESTLPL.PCM| replace:: :download:`BESTLPL.PCM </{docs}/mach/pcm/BESTLPL.PCM/BESTLPL.PCM>`
.. |BESTSOFT.PCM| replace:: :download:`BESTSOFT.PCM </{docs}/mach/pcm/BESTSOFT.PCM/BESTSOFT.PCM>`
.. include:: /{docs}/osys/docrefs.rsti
.. |osys_project| replace:: {osys_project}
.. |osys_author| replace:: {osys_author}
.. include:: /{docs}/osys/cpa/docrefs.rsti
.. |osys_cpa_project| replace:: {osys_cpa_project}
.. |osys_cpa_author| replace:: {osys_cpa_author}
.. |CPA2_85.pdf| replace:: :download:`CPA2#85.PDF </{docs}/osys/cpa/CPA2_85.DOK/CPA2_85.pdf>`
.. |CPA2_85.txt| replace:: :download:`CPA2#85.TXT </{docs}/osys/cpa/CPA2_85.DOK/CPA2_85.txt>`
.. |CPA3_86.dok| replace:: :download:`CPA3#86.DOK </{docs}/osys/cpa/CPA3_86.DOK/CPA3_86.DOK>`
.. |CPA3_86.txt| replace:: :download:`CPA3#86.TXT </{docs}/osys/cpa/CPA3_86.DOK/CPA3_86.TXT>`
.. |CPA3_86.pdf| replace:: :download:`CPA3#86.PDF </{docs}/osys/cpa/CPA3_86.DOK/CPA3_86.pdf>`
.. |CPA4_87.dok| replace:: :download:`CPA4#87.DOK </{docs}/osys/cpa/CPA4_87.DOK/CPA4_87.DOK>`
.. |CPA4_87.rtf| replace:: :download:`CPA4#87.RTF </{docs}/osys/cpa/CPA4_87.DOK/CPA4_87.rtf>`
.. |CPA4_87.txt| replace:: :download:`CPA4#87.TXT </{docs}/osys/cpa/CPA4_87.DOK/CPA4_87.txt>`
.. |CPA4_87.pdf| replace:: :download:`CPA4#87.PDF </{docs}/osys/cpa/CPA4_87.DOK/CPA4_87.pdf>`
.. |CPA5_88.dok| replace:: :download:`CPA5#88.DOK </{docs}/osys/cpa/CPA5_88.DOK/CPA5_88.DOK>`
.. |CPA5_88.rtf| replace:: :download:`CPA5#88.RTF </{docs}/osys/cpa/CPA5_88.DOK/CPA5_88.rtf>`
.. |CPA5_88.txt| replace:: :download:`CPA5#88.TXT </{docs}/osys/cpa/CPA5_88.DOK/CPA5_88.txt>`
.. |CPA5_88.pdf| replace:: :download:`CPA5#88.PDF </{docs}/osys/cpa/CPA5_88.DOK/CPA5_88.pdf>`
.. |CPA6_89.dok| replace:: :download:`CPA6#89.DOK </{docs}/osys/cpa/CPA6_89.DOK/CPA6_89.DOK>`
.. |CPA6_89.rtf| replace:: :download:`CPA6#89.RTF </{docs}/osys/cpa/CPA6_89.DOK/CPA6_89.rtf>`
.. |CPA6_89.txt| replace:: :download:`CPA6#89.TXT </{docs}/osys/cpa/CPA6_89.DOK/CPA6_89.txt>`
.. |CPA6_89.pdf| replace:: :download:`CPA6#89.PDF </{docs}/osys/cpa/CPA6_89.DOK/CPA6_89.pdf>`
.. include:: /{docs}/osys/cpm/docrefs.rsti
.. |osys_cpm_project| replace:: {osys_cpm_project}
.. |osys_cpm_author| replace:: {osys_cpm_author}
'''.format(
    docs = KCS_DOCS,
    publisher = publisher,
    copyright = copyright,
    project = docparts['kcs'].project,
    author = docparts['kcs'].author,
    mach_project = docparts['kcs-mach'].project,
    mach_author = docparts['kcs-mach'].author,
    mach_pcm_project = docparts['kcs-mach-pcm'].project,
    mach_pcm_author = docparts['kcs-mach-pcm'].author,
    osys_project = docparts['kcs-osys'].project,
    osys_author = docparts['kcs-osys'].author,
    osys_cpa_project = docparts['kcs-osys-cpa'].project,
    osys_cpa_author = docparts['kcs-osys-cpa'].author,
    osys_cpm_project = docparts['kcs-osys-cpm'].project,
    osys_cpm_author = docparts['kcs-osys-cpm'].author,
)

# A string of reStructuredText that will be included at the end of every source
# file that is read. This is the right place to add substitutions that should be
# available in every file.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_epilog
#
rst_epilog = u'''
.. include:: /{docs}/termsgloss.rsti
.. include:: /{docs}/termsrobtr.rsti
.. include:: /{docs}/termsecisc.rsti
.. include:: /{docs}/termstgls.rsti
.. include:: /{docs}/docextlnk.rsti
.. include:: /{docs}/docunicode.rsti
'''.format(docs = KCS_DOCS)

# Using variables inside reST w/o 'rst_prolog' or 'rst_epilog'.
ultimate_replacements = {
    '{plot_basedir}': os.path.relpath(plot_basedir, KCS_DOCS),
}

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-internationalization
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-language
#
language = None

# There are two options for replacing |today|.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-today
#
# Either, you set today to some non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-exclude_patterns
#
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.

# This change will allow us to use bare back-tick notation to let
# Sphinx hunt for a reference, starting with normal "document"
# references such as :ref:, but also including :c: and :cpp: domains
# (potentially) helping with API (doxygen) references simply by using
# `name`
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-primary_domain
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-default_role
#
#primary_domain = 'cpp'
default_role = 'any'

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_function_parentheses
#
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-add_module_names
#
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-show_authors
#
#show_authors = False
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-pygments_style
#
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-modindex_common_prefix
#
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-keep_warnings
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-suppress_warnings
#
#keep_warnings = False
#suppress_warnings = []

# If true, figures, tables and code-blocks are automatically numbered if they
# have a caption. At same time, the numref role is enabled. For now, it works
# only with the HTML builder and LaTeX builder. Default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig
#
numfig = True

# A dictionary mapping 'figure', 'table' and 'code-block' to strings that are
# used for format of figure numbers. Default is to use 'Fig. %s' for 'figure',
# 'Table %s' for 'table' and 'Listing %s' for 'code-block'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_format
#
numfig_format = {
    'code-block': 'Listing %s',
    'sections': 'Section %s',
    'figure': 'Figure %s',
    'table': 'Table %s',
}

# The scope of figure numbers, that is, the numfig feature numbers figures in
# which scope. 0 means “whole document”. 1 means “in a section”. Sphinx numbers
# like x.1, x.2, x.3... 2 means “in a subsection”. Sphinx numbers like x.x.1,
# x.x.2, x.x.3..., and so on. Default is 1.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_secnum_depth
#
numfig_secnum_depth = 1

# Set this option to True if you want all displayed math to be numbered.
# The default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_number_all
#
math_number_all = True

# A string used for formatting the labels of references to equations. The
# {number} place-holder stands for the equation number. Example: 'Eq.{number}'
# gets rendered as, for example, Eq.10.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_eqref_format
#
math_eqref_format = 'Equastion {number}'

# If True, displayed math equations are numbered across pages when numfig is
# enabled. The numfig_secnum_depth setting is respected. The eq, not numref,
# role must be used to reference equation numbers. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_numfig
#
# math_numfig = False

# A URL to cross-reference manpage directives.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-manpages_url
#
manpages_url = 'https://manpages.debian.org/{path}'

# A User-Agent of Sphinx. It is used for a header on HTTP access
# (ex. linkcheck, intersphinx and so on).
# Default is "Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-user_agent
#
#user_agent = 'Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z

# If true, Sphinx verifies server certifications. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_verify
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_cacerts
#
#tls_verify = False

# some configuration for linkcheck builder
#   noticed that we're getting false-positive link errors on different server,
#   I suspect because it's taking too long for the server to respond so bump
#   up the timeout (default=5) and turn off anchor checks (so only a HEAD
#   request is done - much faster). Leave the ignore commented in case we want
#   to remove different server link checks later...

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_ignore
#
#linkcheck_ignore = [r'http://localhost:\d+/']
linkcheck_ignore = [
    r'https://terminals-wiki.org/',  # Causes 500 Server Error: internal server error
    r'https://www.mugler.de/',  # Causes SSLError: certificate verify failed
    # This server's certificate chain is incomplete. Grade capped to B:
    # https://www.ssllabs.com/ssltest/analyze.html?d=www.mugler.de&hideResults=on
    r'http://localhost:\d+/',
]

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_timeout
#
linkcheck_timeout = 60

# The number of worker threads to use when checking links.
# Default is 5 threads.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_workers
#
# linkcheck_workers = 5
linkcheck_workers = 10

# True or false, whether to check the validity of #anchors in links.
# Since this requires downloading the whole document, it’s considerably
# slower when enabled. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors_ignore
#
#linkcheck_anchors = True
linkcheck_anchors = False


# -- Options for HTML output ----------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-output
#

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_path
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_options
#
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_theme_options = {
    'prev_next_buttons_location': None,
    'style_external_links': True,
    'titles_only': False,
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 6,
}

if tags.has('release'):  # pylint: disable=undefined-variable
    is_release = True
    docs_title = 'Docs / %s' %(version)
else:
    is_release = False
    docs_title = 'Docs / Latest'

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_title
#
html_title = "KC-Systems Project Documentation"

# This value determines the text for the permalink; it defaults to "¶".
# Set it to None or the empty string to disable permalinks.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_add_permalinks
#
#html_add_permalinks = ""

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_short_title
#
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_logo
#
html_logo = '{}/_images/lpn.svg'.format(KCS_DOCS)

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_favicon
#
html_favicon = '{}/_images/lpn.ico'.format(KCS_DOCS)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_static_path
#
html_static_path = ['{}/_static'.format(KCS_DOCS)]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_extra_path
#
# html_extra_path = ['{}/_extra'.format(KCS_DOCS)]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_last_updated_fmt
#
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_smartypants
#
#html_use_smartypants =

# Custom sidebar templates, maps document names to template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sidebars
#
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_additional_pages
#
#html_additional_pages = {}

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_domain_indices
#
html_domain_indices = False

# If false, no index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_index
#
html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_split_index
#
html_split_index = True

# If true, links to the reST sources are added to the pages.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sourcelink
#
html_show_sourcelink = False

# Suffix to be appended to source links.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sourcelink_suffix
#
html_sourcelink_suffix = '.txt'

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sphinx
#
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_copyright
#
# html_show_copyright = tags.has('development')

# If true, license is shown in the HTML footer. Default is True.
html_show_license = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_opensearch
#
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_file_suffix
#
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_language
#
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_options
#
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_scorer
#
html_search_scorer = '{}/_static/js/scorer.js'.format(KCS_DOCS)

# Custom added feature to allow redirecting old URLs (caused by
# reorganizing doc directories)
#
# list of tuples (old_url, new_url) for pages to redirect
#
# URLs must be relative to document root (with NO leading slash),
# and without the html extension)
html_redirect_pages = [
    ('releases/release-notes', 'releases/index'),
]


# -- Options for HTML help output -----------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-help-output
#

# Output file base name for HTML help builder.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-htmlhelp_basename
#
htmlhelp_basename = 'kcsystemsdoc'


# -- Options for LaTeX output ---------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/latex.html
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-latex-output
#
# https://www.sphinx-doc.org/en/master/latex.html
# https://blog.michael.franzl.name/2014/12/10/xelatex-unicode-font-fallback-unsupported-characters/
# https://tex.stackexchange.com/questions/344100/
# https://tex.stackexchange.com/questions/323575/

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_additional_files
#
#latex_additional_files = [
#    '{}/_extra/file.ext'.format(KCS_DOCS),
#]

# TODO: evaluate possible admonitionbox override, see:
#       http://stackoverflow.com/a/13661732
# Left aligne captions: http://tex.stackexchange.com/questions/136688/how-to-align-caption-with-table

# The LaTeX engine to build the docs. The setting can have the
# following values:
#   'pdflatex' – PDFLaTeX (default)
#   'xelatex' – XeLaTeX
#   'lualatex' – LuaLaTeX
#   'platex' – pLaTeX (default if language is 'ja')
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_engine
#
latex_engine = 'xelatex'

f = open('{}/_templates/extrapackages.tex'.format(KCS_DOCS), 'r+')
latex_custom_extrapackages = f.read()

f = open('{}/_templates/passoptstopackages.tex.in'.format(KCS_DOCS), 'r+')
latex_custom_passoptionstopackages = f.read().format (
    producer = r'Sphinx ' + build_sphinx,
    creator = r'Sphinx ' + build_sphinx,
    subject = docparts['kcs'].project,
    keywords = keywords,
)

f = open('{}/_templates/preamble.tex'.format(KCS_DOCS), 'r+')
latex_custom_preamble = f.read()

f = open('{}/_templates/fontpkg.tex'.format(KCS_DOCS), 'r+')
latex_custom_fontpkg = f.read()

f = open('{}/_templates/utf8extra.tex'.format(KCS_DOCS), 'r+')
latex_custom_utf8extra = f.read()

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_elements
# http://www.sphinx-doc.org/en/3.x/latex.html
#
latex_elements = {
    #
    # Keys that you may want to override include:
    #
    'extraclassoptions': 'table',

    # Paper size option of the document class ('letterpaper' or 'a4paper'),
    # default 'letterpaper'.
    'papersize': 'a4paper',

    # Point size option of the document class ('10pt', '11pt' or '12pt'),
    # default '10pt'.
    'pointsize': '10pt',

    # "babel" package inclusion, default r'\usepackage{babel}'.
    'babel': r'\usepackage[english]{babel}',

    # "geometry" package inclusion, default r'\usepackage{geometry}'.
    'geometry': r'\usepackage[bottom=4cm, left=2.4cm, right=2.4cm]{geometry}',

    # Font package inclusion, default r'\usepackage{times}' (which uses Times
    # and Helvetica). You can set this to '' to use the Computer Modern fonts.
    # Defaults to '' when the language uses the Cyrillic script.
    # For xelatex it defaults to: r'''\setmainfont{FreeSerif}[..]
    # \setsansfont{FreeSans}[..]\setmonofont{FreeMono}[..]'''
    'fontpkg': latex_custom_fontpkg,

    # Inclusion of the "fncychap" package (which makes fancy chapter titles),
    # default r'\usepackage[Bjarne]{fncychap}' for English documentation,
    # r'\usepackage[Sonny]{fncychap}' for internationalized docs (because the
    # "Bjarne" style uses numbers spelled out in English). Other "fncychap"
    # styles you can try include "Lenny", "Glenn", "Conny" and "Rejne". You can
    # also set this to '' to disable fncychap.
#   'fncychap': r'\usepackage[Sonny]{fncychap}',
#   'fncychap': r'\usepackage[Bjarne]{fncychap}',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',

    # Additional package inclusion, default empty.
    'extrapackages': latex_custom_extrapackages,

    # "PassOptionsToPackage" call, default empty.
    'passoptionstopackages': latex_custom_passoptionstopackages,

    # Additional preamble content, default empty.
    'preamble': latex_custom_preamble,

    # Latex figure (float) alignment, default 'htbp' (here, top, bottom, page).
    # Whenever an image doesn't fit into the current page, it will be 'floated'
    # into the next page but may be preceded by any other text. If you don't
    # like this behavior, use 'H' which will disable floating and position
    # figures strictly in the order they appear in the source.
    'figure_align': 'H',

    # Latex number figure format, default empty.
#   'numfig_format': '',

    #
    # Keys that don’t need be overridden unless in special cases are:
    #

    # "inputenc" package inclusion, defaults to r'\usepackage[utf8]{inputenc}'
    # when using pdflatex. Otherwise unset.
#   'inputenc': r'\usepackage[utf8]{inputenc}',

    # Unicode character declaration, for xelatex defaults to:
    # \catcode`^^^^00a0\active\protected\def^^^^00a0{\leavevmode\nobreak\ }
    'utf8extra': latex_custom_utf8extra,

    # "cmap" package inclusion, default r'\usepackage{cmap}'.
#   'cmappkg': r'\usepackage{cmap}',

    # "fontenc" package inclusion, default r'\usepackage[T1]{fontenc}' and
    # r'\usepackage{fontspec}\defaultfontfeatures[\rmfamily,\sffamily,\ttfamily]{}'
    # in case of xelatex for non-mandarin languages.
#   'fontenc': r'\usepackage[T1]{fontenc}',

    # "amsmath" package inclusion, default r'\usepackage{amsmath,amssymb,amstext}'.
#   'amsmath': r'\usepackage{amsmath,amssymb,amstext}',

    # Value that prefixes 'release' element on title page, default 'Release'.
    'releasename': 'Version',

    # "makeindex" call, default r'\makeindex'. Override if you want to
    # generate a differently-styled index page.
#   'makeindex': r'\makeindex',

    # "maketitle" call, default r'\sphinxmaketitle'. Override if you want to
    # generate a differently-styled title page.
#   'maketitle': r'\sphinxmaketitle',

    # "tableofcontents" call, default r'\sphinxtableofcontents'. Override if
    # you want to generate a different table of contents or put content between
    # the title page and the TOC.
#   'tableofcontents': r'\sphinxtableofcontents',

    # "printindex" call, the last thing in the file, default r'\printindex'.
    # Override if you want to generate the index differently or append some
    # content after the index.
    'printindex': r'\footnotesize\raggedright\printindex',

    # Commands used to display transitions, default r'\n\n\bigskip\hrule{}\bigskip\n\n'.
    # Override if you want to display transitions differently.
#   'transition': r'\n\n\bigskip\hrule{}\bigskip\n\n',

    #
    # Keys that are set by other options and therefore should not be
    # overridden are: 'docclass' 'classoptions' 'extraclassoptions'
    #                 'contentsname' 'title' 'date' 'release'
    #                 'author' 'logo' 'makeindex' 'shorthandoff'
    #                 'tocdepth' 'pageautorefname'
    #

    # Get rid of evenly numbered empty pages (default book style)
#   'classoptions': ',openany,oneside',
    'classoptions': ',openany',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_documents
#
latex_documents = [
  (docparts['kcs'].master, 'kcsystems.tex', docparts['kcs'].project + u' Documentation',
   docparts['kcs'].author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_logo
#
#latex_logo = None
latex_logo = '{}/_images/lpn.pdf'.format(KCS_DOCS)

# If true, show page references after internal links. Default: False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_show_pagerefs
#
latex_show_pagerefs = True

# If true, show URL addresses after external links. Default: 'no'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_show_urls
#
# latex_show_urls = 'no'
# latex_show_urls = 'footnote'
# latex_show_urls = 'inline'

# Documents to append as an appendix to all manuals.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_appendices
#
#latex_appendices = [
#    'appendix/howtos',
#    'glossrobotron',
#    'glossecisc',
#    'glosstgls',
#    'glossary',
#    'bibliography',
#]

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_domain_indices
#
#latex_domain_indices = True


# -- Options for Text output ----------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-text-output
#

# Determines which end-of-line character(s) are used in text
# output: 'unix', 'windows', or 'native'. Default: 'unix'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-text_newlines
#
# text_newlines = 'unix'

# A string of 7 characters that should be used for underlining
# sections. The first character is used for first-level headings,
# the second for second-level headings and so on. The default is '*=-~"+`'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-text_sectionchars
#
text_sectionchars = '*=-~"+`'


# -- Options for manual page output ---------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-manual-page-output
#

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-man_pages
#
#man_pages = [
#    (docparts['kcs'].master, 'kcsystems', docparts['kcs'].project + u' Documentation',
#     [docparts['kcs'].author], 1)
#]

# If true, show URL addresses after external links.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-man_show_urls
#
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-texinfo-output
#

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_documents
#
#texinfo_documents = [
#  (docparts['kcs'].master, 'kcsystems', docparts['kcs'].project + u' Documentation',
#   docparts['kcs'].author, 'KC-Systems', 'One line description of project.',
#   'Miscellaneous'),
#]

# Documents to append as an appendix to all manuals.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_appendices
#
#texinfo_appendices = []

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_domain_indices
#
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_show_urls
#
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-texinfo_no_detailmenu
#
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-epub-output
#

# Bibliographic Dublin Core info.
epub_title = docparts['kcs'].project
epub_author = docparts['kcs'].author
epub_publisher = publisher
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
epub_basename = u'kcsystems'

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# -- Options for Breathe input --------------------------------------------

#breathe_projects = {
#    "KC-Systems": "{}/doxygen/xml".format(KCS_BUILD),
#    "doc-examples": "{}/doxygen/xml".format(KCS_BUILD)
#}
#breathe_default_project = "KC-Systems"

# Changing breathe configuration to force "c" domain doesn't work
# see https://github.com/michaeljones/breathe/issues/282
#breathe_domain_by_extension = {
#    "h" : "c",
#    "c" : "c",
#    }

# Qualifiers to a function are causing Sphihx/Breathe to warn about
# Error when parsing function declaration and more.  This is a list
# of strings that the parser additionally should accept as
# attributes.
#cpp_id_attributes = ['__syscall', '__deprecated',
#    '__may_alias', '__used', '__unused', '__weak',
#    '__DEPRECATED_MACRO', 'FUNC_NORETURN']


# -- Options for Breadcrumb output ----------------------------------------

# docs_title is used in the breadcrumb title in the kcsystems docs theme
html_context = {
    'show_license': html_show_license,
    'docs_title': docs_title,
    'is_release': is_release,
    'theme_logo_only': False,
    'current_version': version,
    'versions': (("latest", "/"),
                 ("1.0.0", "/1.0.0/"),
                )
}
