#####
#
# Build Information
#
$(call bi,set,osys,name,"CP/A")

ifeq ($(CONFIG_CPA_198703),y)
include $(S)1987-03/Makefile
endif

# Local variables:
# coding: utf-8
# mode: text
# mode: make
# End:
# vim: fileencoding=utf-8 filetype=make :
