.. External Links:

.. _`TGL Catalog (EWN)`: http://www.wak-gmbh.de/index.php?id=40&L=5
.. _`TGL Catalog (BHU Weimar)`: http://www.uni-weimar.de/de/universitaet/struktur/zentrale-einrichtungen/universitaetsbibliothek/recherche/normen/tgl-verzeichnis/
.. _`TGL Archive (BBSR)`: https://www.bbr-server.de/bauarchivddr/finbuch/tgl/index.htm
.. _`TGL Archive`: http://tgl-archiv.de/

.. _`Computer Museum, University of Stuttgart`: http://computermuseum.informatik.uni-stuttgart.de/
.. _`CM ftp area for PC1715`: ftp://ftp.informatik.uni-stuttgart.de/pub/cm/robotron/pc1715/
.. _`cpa.txt`: ftp://ftp.informatik.uni-stuttgart.de/pub/cm/robotron/pc1715/CPA/cpa.txt

.. _`Elmar Klinder and Götz Hupe`: http://www.mpm-kc85.de/
.. _`SCP area (EKGH)`: http://www.mpm-kc85.de/html/Assembler.htm#SCP

.. _`Holm Tiffe`: http://www.tiffe.de/
.. _`CP/A area (HT)`: http://www.tiffe.de/Robotron/CPA/
.. _`cpa-enrico.zip`: http://www.tiffe.de/Robotron/CPA/cpa-enrico/CPA.zip
.. _`PC1715 area (HT)`: http://www.tiffe.de/Robotron/PC1715/
.. _`SCP area (HT)`: http://www.tiffe.de/Robotron/SCP/

.. _`Digital AG`: http://www.digital-ag.de.vu/
.. _`Bürocomputer 8-Bit`: http://9hal.ath.cx/usr/digital-ag/archiv/#B%C3%BCrocomputer%208-Bit
.. _`Beschreib_CPA.pdf`: http://9hal.ath.cx/usr/digital-ag/archiv/handbuecher/Beschreibung_des_Betriebssystems_CPA.pdf

.. .. _`Volker Pohlers`: http://www.homecomputer-ddr.de.vu/
.. .. _`CP/A area (VP)`: http://www.homecomputer-ddr.de.vu/wiki/doku.php/cpm:cpa
.. .. _`SCP area (VP)`: http://www.homecomputer-ddr.de.vu/wiki/doku.php/cpm:m80#scpasm_link_lib
.. .. _`cpa.zip`: http://www.homecomputer-ddr.de.vu/wiki/lib/exe/fetch.php/cpm:cpa.zip
.. _`Volker Pohlers`: http://hc-ddr.hucki.net/
.. _`CP/A area (VP)`: http://hc-ddr.hucki.net/wiki/doku.php/cpm:cpa
.. _`SCP area (VP)`: http://hc-ddr.hucki.net/wiki/doku.php/cpm:m80#scpasm_link_lib
.. _`cpa.zip`: http://hc-ddr.hucki.net/wiki/lib/exe/fetch.php/cpm:cpa.zip

.. _`Ulrich Zander`: http://www.sax.de/~zander/
.. _`PC1715 area (UZ)`: http://www.sax.de/~zander/index2h.html
.. _`KC85 area (UZ)`: http://www.sax.de/~zander/index2h.html
.. _`Z9001 / KC87 area (UZ)`: http://www.sax.de/~zander/index2h.html
.. _`Z1013 area (UZ)`: http://www.sax.de/~zander/index2h.html

.. .. _`Jörg Felgentreu`: http://felgentreu.dyndns.org/
.. .. _`PC1715 area (JF)`: http://felgentreu.dyndns.org/robotron/pc1715.htm
.. .. _`K1520 area (JF)`: http://felgentreu.dyndns.org/robotron/k1520doku.htm
.. _`Jörg Felgentreu`: http://felgentreu.spdns.org/
.. _`PC1715 area (JF)`: http://felgentreu.spdns.org/robotron/pc1715.htm
.. _`K1520 area (JF)`: http://felgentreu.spdns.org/robotron/k1520doku.htm

.. _`KC-Club`: http://www.kcclub.de/
.. _`Rubrik 26: Dokumentationen für CP/M und MicroDOS`: http://www.kcclub.de/dlarchiv/09/RUBRIK26.HTM
.. _`PC_M1.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_M1.DOC
.. _`PC_M2.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_M2.DOC
.. _`PC_M3.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_M3.DOC
.. _`PC_M4.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_M4.DOC
.. _`PC_MBUSK.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_MBUSK.DOC
.. _`PC_MEPT.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_MEPT.DOC
.. _`PC_M7659.DOC`: http://www.kcclub.de/dlarchiv/DOWNLOAD/DISK269/PC_M7659.DOC

.. _`Lagerplatz von Li-Pro.Net`: http://store.li-pro.net/
.. _`PC/M Floppy Disk Images`: http://store.li-pro.net/index.php?dir=pcm/fdimages/
.. _`IFSSV24.DOC`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=IFSSV24.DOC
.. _`UMBA2732.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=UMBA2732.PCM
.. _`INTERROR.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=INTERROR.PCM
.. _`SYSINFO.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=SYSINFO.PCM
.. _`BESTLPL.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=BESTLPL.PCM
.. _`BESTSOFT.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk03-orig-19901030/&file=BESTSOFT.PCM
.. _`LESEDAS.PCM`: http://store.li-pro.net/index.php?dir=pcm/fdimages/pcmdsk01-orig-19901030/&file=LESEDAS.PCM

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
