.. Abstract:

.. |dm_abstract| replace:: This document has documentation of the |KC|-Systems
   project |version| which is a community effort to improve the configuration
   and build process of different operating systems for different historical
   Zilog Z80 (|U880|) based computer systems made in |GDR| that was so called
   |Kleincomputer| in German.

.. |dm_mach_abstract| replace:: This document has the documentation about
   different historical computer systems that are supported by the
   |KC|-Systems project |version|.

.. |dm_mach_pcm_abstract| replace:: This document has the documentation about
   the Mugler-/Mathes-PC, shortly the |PC/M|, that is supported by the
   |KC|-Systems project |version|.

.. |dm_osys_abstract| replace:: This document has the documentation about
   different historical operating systems that are supported by the
   |KC|-Systems project |version|.

.. |dm_osys_cpa_abstract| replace:: This document has the documentation about
   the Operating System |CP/A| developed by the Academy of Sciences of the |GDR|
   for the Office Cumputer |A5120|/|A5130|, |PC1715| and simular systems that is
   supported by the |KC|-Systems project |version|.

.. |dm_osys_cpm_abstract| replace:: This document has the documentation about
   the Operating System |CP/M| developed by Gary Kildall, founder of Digital
   Research, Inc. for Intel 8080 and Zilog Z80 based computer systems.

.. |dm_rn_abstract| replace:: This document has the release notes of the
   |KC|-Systems project |version| which is a community effort to improve the
   configuration and build process of different operating systems for
   different historical Zilog Z80 (|U880|) based computer systems made in |GDR|
   that was so called |Kleincomputer| in German.


.. Target Audience:

.. |dm_target| replace:: users, developers and integrators
.. |dm_status| replace:: some mature, some in progress

.. |dm_mach_target| replace:: |dm_target|
.. |dm_mach_status| replace:: |dm_status|

.. |dm_mach_pcm_target| replace:: |dm_target|
.. |dm_mach_pcm_status| replace:: |dm_status|

.. |dm_osys_target| replace:: |dm_target|
.. |dm_osys_status| replace:: |dm_status|

.. |dm_osys_cpa_target| replace:: |dm_target|
.. |dm_osys_cpa_status| replace:: |dm_status|

.. |dm_osys_cpm_target| replace:: |dm_target|
.. |dm_osys_cpm_status| replace:: |dm_status|

.. |dm_rn_target| replace:: |dm_target|
.. |dm_rn_status| replace:: |dm_status|


.. Copyright:

.. |dm_copyright| replace:: Copyright |copy| 2014, |LPN| |---|
   all rights reserved. This work is licensed under a Creative Commons
   Attribution-ShareAlike 3.0 Unported License (`CC-BY-SA-3.0`_).
   See the file |LICENSE| and |CREDITS| that comes with
   the documentation.

.. |dm_mach_copyright| replace:: |dm_copyright|

.. |dm_mach_pcm_copyright| replace:: Copyright |copy| 1986,1987,1988,1989,1990,
   |dm_mach_pcm_organization| |---| all rights reserved.

.. |dm_osys_copyright| replace:: |dm_copyright|

.. |dm_osys_cpa_copyright| replace:: Copyright |copy| 1985,1986,1987,1988,1989,
   |dm_osys_cpa_organization| |---| all rights reserved.

.. |dm_osys_cpm_copyright| replace:: Copyright |copy| 1974
   |dm_osys_cpm_organization| |---| all rights reserved.

.. |dm_rn_copyright| replace:: |dm_copyright|


.. Organization:

.. |dm_organization| replace:: |publisher|
.. |dm_address| replace:: Jena, Germany
.. |dm_contact_obfuscated| replace:: |slz_obfuscated|
.. |dm_contact_plain_text| replace:: |slz_plain_text|

.. |dm_mach_organization| replace:: |dm_organization|
.. |dm_mach_address| replace:: |dm_address|
.. |dm_mach_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_mach_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_mach_pcm_organization| replace:: |pdamu|, |hma| and |ube|
.. |dm_mach_pcm_address| replace:: Karl-Marx-Stadt, |GDR|
.. |dm_mach_pcm_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_mach_pcm_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_osys_organization| replace:: |dm_organization|
.. |dm_osys_address| replace:: |dm_address|
.. |dm_osys_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_osys_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_osys_cpa_organization| replace:: Academy of Sciences of the |GDR|
.. |dm_osys_cpa_address| replace:: Berlin, |GDR|
.. |dm_osys_cpa_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_osys_cpa_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_osys_cpm_organization| replace:: |dm_organization|
.. |dm_osys_cpm_address| replace:: |dm_address|
.. |dm_osys_cpm_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_osys_cpm_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_rn_organization| replace:: |dm_organization|
.. |dm_rn_address| replace:: |dm_address|
.. |dm_rn_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_rn_contact_plain_text| replace:: |dm_contact_plain_text|


.. Authors:

.. |amu| replace:: Albrecht Mugler
.. |dramu| replace:: Dr. |amu|
.. |pdamu| replace:: Prof. |dramu|
.. |amu_obfuscated| replace:: :email:`Albrecht Mugler <amu@amu.de>`
.. |dramu_obfuscated| replace:: :email:`Dr. Albrecht Mugler <amu@amu.de>`
.. |pdamu_obfuscated| replace:: :email:`Prof. Dr. Albrecht Mugler <amu@amu.de>`
.. |amu_plain_text| replace:: Albrecht Mugler <amu@amu.de>
.. |dramu_plain_text| replace:: Dr. Albrecht Mugler <amu@amu.de>
.. |pdamu_plain_text| replace:: Prof. Dr. Albrecht Mugler <amu@amu.de>

.. |aosgdr| replace:: Academy of Sciences of the |GDR|
.. |aosgdricst| replace:: |aosgdr|, Institute of computer science and technology
.. |aosgdr_obfuscated| replace:: |aosgdr|
.. |aosgdr_plain_text| replace:: |aosgdr|

.. |hma| replace:: Herbert Mathes
.. |hma_obfuscated| replace:: :email:`Herbert Mathes <hma@hma.de>`
.. |hma_plain_text| replace:: Herbert Mathes <hma@hma.de>

.. |slz| replace:: Stephan Linz
.. |slz_obfuscated| replace:: :email:`Stephan Linz <linz@li-pro.net>`
.. |slz_plain_text| replace:: Stephan Linz <linz@li-pro.net>

.. |ube| replace:: Uwe Beer
.. |ube_obfuscated| replace:: :email:`Uwe Beer <ube@ube.de>`
.. |ube_plain_text| replace:: Uwe Beer <ube@ube.de>


.. Licenses:

.. _`CC-BY-SA-3.0`: http://creativecommons.org/licenses/by-sa/3.0/


.. Unicodes:

.. |LPN| unicode:: Li U+02013 Pro.Net


.. spelling::

   Mugler
   Albrecht
   Mathes
   Herbert
   Linz
   Stephan
   Beer
   Uwe

.. spelling::

   docsummary
   pcm
   Todo

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
