.. Roles:

.. role:: strikethrough

.. role:: addr(code)
   :language: nasm
   :class: highlight

.. role:: code(code)
   :language: nasm
   :class: highlight

.. role:: port(code)
   :language: nasm
   :class: highlight

.. role:: console(code)
   :language: console
   :class: highlight

.. role:: nasm(code)
   :language: nasm
   :class: highlight

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
