.. only:: html

   .. sidebar:: Summary

      :Version:		|version|
      :Release:		|release|
      :Date:		|today|
      :Status:		|dm_status|
      :Contact:		|dm_contact_obfuscated|
      :Organization:	|dm_organization|
      :Address:		|dm_address|
      :Copyright:	|dm_copyright|
      :Authors:		|author|

			* |slz_obfuscated|

      :Abstract:	|dm_abstract|
      :Target:		|dm_target|

.. only:: latex

   .. sidebar:: Summary of |project|

      :Version:		|version|
      :Release:		|release|
      :Date:		|today|
      :Status:		|dm_status|
      :Contact:		|dm_contact_plain_text|
      :Organization:	|dm_organization|
      :Address:		|dm_address|
      :Copyright:	|dm_copyright|
      :Authors:		|author|

			* |slz_plain_text|

      :Abstract:	|dm_abstract|
      :Target:		|dm_target|

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
