.. Unicodes:

.. |nbsp| unicode:: U+000A0 
   :trim:
.. |curs| unicode:: U+000A4 .. currency sign (the old German "pig")
.. |copy| unicode:: U+000A9 .. copyright sign
.. |regs| unicode:: U+000AE .. registered sign
.. |oneq| unicode:: U+000BC .. vulgar fraction one quarter
.. |oneh| unicode:: U+000BD .. vulgar fraction one half
.. |threeq| unicode:: U+000BE .. vulgar fraction three quarters

.. |Omega| unicode:: U+003A9 .. Greek capital letter omagea
.. |theta| unicode:: U+003D1 .. Greek theta symbol

.. |--| unicode:: U+02013 .. en dash
   :trim:
.. |---| unicode:: U+02014 .. em dash
   :trim:
.. |...| unicode:: U+02026 .. three dot leader
   :trim:
.. |tm| unicode:: U+02122 .. trade mark

.. |degc| unicode:: U+02103 .. degree celsius
.. |degf| unicode:: U+02109 .. degree fahrenheit

.. |CLT| unicode:: U+02190 .. cursor left sign
.. |CUP| unicode:: U+02191 .. cursor up sign
.. |CRT| unicode:: U+02192 .. cursor right sign
.. |CDN| unicode:: U+02193 .. cursor down sign
.. |CHO| unicode:: U+02196 .. cursor home sign
.. |CLB| unicode:: U+021E4 .. cursor left to bar sign
.. |CRB| unicode:: U+021E5 .. cursor right to bar sign
.. |CDL| unicode:: U+021B5 .. cursor down-left sign
.. |CLRB| unicode:: U+021B9 .. cursor left-right to bar sign

.. |sup0| unicode:: U+02070 .. superscript zero
   :trim:
.. |sup1| unicode:: U+000B9 .. superscript one
   :trim:
.. |sup2| unicode:: U+000B2 .. superscript two
   :trim:
.. |sup3| unicode:: U+000B3 .. superscript three
   :trim:
.. |sup4| unicode:: U+02074 .. superscript four
   :trim:
.. |sup5| unicode:: U+02075 .. superscript five
   :trim:
.. |sup6| unicode:: U+02076 .. superscript six
   :trim:
.. |sup7| unicode:: U+02077 .. superscript seven
   :trim:
.. |sup8| unicode:: U+02078 .. superscript eight
   :trim:
.. |sup9| unicode:: U+02079 .. superscript nine
   :trim:
.. |sup+| unicode:: U+0207A .. superscript plus sign
   :trim:
.. |sup-| unicode:: U+0207B .. superscript minus sign
   :trim:
.. |sup=| unicode:: U+0207C .. superscript equal sign
   :trim:
.. |sup(| unicode:: U+0207D .. superscript left parenthesis
   :trim:
.. |sup)| unicode:: U+0207E .. superscript right parenthesis
   :trim:

.. |sub0| unicode:: U+02080 .. subscript zero
   :trim:
.. |sub1| unicode:: U+02081 .. subscript one
   :trim:
.. |sub2| unicode:: U+02082 .. subscript two
   :trim:
.. |sub3| unicode:: U+02083 .. subscript three
   :trim:
.. |sub4| unicode:: U+02084 .. subscript four
   :trim:
.. |sub5| unicode:: U+02085 .. subscript five
   :trim:
.. |sub6| unicode:: U+02086 .. subscript six
   :trim:
.. |sub7| unicode:: U+02087 .. subscript seven
   :trim:
.. |sub8| unicode:: U+02088 .. subscript eight
   :trim:
.. |sub9| unicode:: U+02089 .. subscript nine
   :trim:
.. |sub+| unicode:: U+0208A .. subscript plus sign
   :trim:
.. |sub-| unicode:: U+0208B .. subscript minus sign
   :trim:
.. |sub=| unicode:: U+0208C .. subscript equal sign
   :trim:
.. |sub(| unicode:: U+0208D .. subscript left parenthesis
   :trim:
.. |sub)| unicode:: U+0208E .. subscript right parenthesis
   :trim:

.. |+-| unicode:: U+000B1 .. plus minus sign
   :rtrim:
.. |x| unicode:: U+000D7 .. multiplication operator
   :trim:
.. |/| unicode:: U+02044 .. devision operator
   :trim:
.. |*| unicode:: U+022C5 .. multiplication operator
   :trim:

.. |uH| unicode:: U+000B5 H .. micro henry
   :rtrim:
.. |mH| unicode:: mH .. milli henry

.. |pA| unicode:: U+03380 .. pico ampere
.. |nA| unicode:: U+03381 .. nano ampere
.. |uA| unicode:: U+03382 .. micro ampere
.. |mA| unicode:: U+03383 .. milli ampere
.. |kA| unicode:: U+03384 .. kilo ampere

.. |kb| replace:: kbit

.. |kB| unicode:: U+03385 .. kilo byte
.. |MB| unicode:: U+03386 .. mega byte
.. |GB| unicode:: U+03387 .. giga byte

.. |pF| unicode:: U+0338A .. pico farad
.. |nF| unicode:: U+0338B .. nano farad
.. |uF| unicode:: U+0338C .. micro farad

.. |ug| unicode:: U+0338D .. micro gramm
.. |mg| unicode:: U+0338E .. milli gramm
.. |kg| unicode:: U+0338F .. kilo gramm

.. |Hz| unicode:: U+03390 .. hertz
.. |kHz| unicode:: U+03391 .. kilo hertz
.. |MHz| unicode:: U+03392 .. mega hertz
.. |GHz| unicode:: U+03393 .. giga hertz
.. |THz| unicode:: U+03394 .. tera hertz

.. |nm| unicode:: U+0339A .. nano meter
.. |um| unicode:: U+0339B .. micro meter
.. |mm| unicode:: U+0339C .. milli meter
.. |cm| unicode:: U+0339D .. centi meter
.. |km| unicode:: U+0339E .. kilo meter

.. |ps| unicode:: U+033B0 .. pico second
.. |ns| unicode:: U+033B1 .. nano second
.. |us| unicode:: U+033B2 .. micro second
.. |ms| unicode:: U+033B3 .. milli second

.. |pV| unicode:: U+033B4 .. pico volt
.. |nV| unicode:: U+033B5 .. nano volt
.. |uV| unicode:: U+033B6 .. micro volt
.. |mV| unicode:: U+033B7 .. milli volt
.. |kV| unicode:: U+033B8 .. kilo volt
.. |MV| unicode:: U+033B9 .. mega volt

.. |pW| unicode:: U+033BA .. pico watt
.. |nW| unicode:: U+033BB .. nano watt
.. |uW| unicode:: U+033BC .. micro watt
.. |mW| unicode:: U+033BD .. milli watt
.. |kW| unicode:: U+033BE .. kilo watt
.. |MW| unicode:: U+033BF .. mega watt

.. |kO| unicode:: U+033C0 .. kilo ohm
.. |MO| unicode:: U+033C1 .. mega ohm

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
