.. Glossary Replacements:

.. |bps| replace:: Bit |*| s |sup-| |sup1|
.. |Bps| replace:: Byte |*| s |sup-| |sup1|


.. Commons:

.. |AdW der DDR|                    replace:: :term:`AdW der DDR`
.. |AoS of the GDR|                 replace:: :term:`AoS of the GDR`
.. |GDR|                            replace:: :term:`GDR`
.. |DDR|                            replace:: :term:`DDR`
.. |TGL|                            replace:: :term:`TGL`
.. |KC|                             replace:: :term:`KC`
.. |Kleincomputer|                  replace:: :term:`Kleincomputer`
.. |Minicomputer from Mühlhausen|   replace:: :term:`Minicomputer from Mühlhausen`
.. |Minicomputer from Dresden|      replace:: :term:`Minicomputer from Dresden`
.. |Minicomputer from Riesa|        replace:: :term:`Minicomputer from Riesa`
.. |Minicomputer Construction Kit|  replace:: :term:`Minicomputer Construction Kit`

.. |VEB Buchungsmaschinenwerk Karl-Marx-Stadt| replace:: :rtloc:`VEB Buchungsmaschinenwerk Karl-Marx-Stadt <buma.htm>`
.. |VEB Büromaschinenwerk Sömmerda|            replace:: :rtloc:`VEB Büromaschinenwerk "Ernst Thälmann" Sömmerda <bws.htm>`
.. |VEB Mikroelektronik Mühlhausen|            replace:: :rtloc:`VEB Mikroelektronik Mühlhausen <mpm.htm>`
.. |VEB Robotron Otto Schön|                   replace:: :rtloc:`VEB Robotron-Meßelektronik "Otto Schön" <ottoschoen.htm>`
.. |VEB Robotron Riesa|                        replace:: :rtloc:`VEB Robotron-Elektronik Riesa <relektronik_riesa.htm>`


.. Journals:

.. |FA|                             replace:: :term:`FA`
.. |Funkamateur|                    replace:: :term:`Funkamateur`
.. |MP|                             replace:: :term:`MP`
.. |Mikroprozessortechnik|          replace:: :term:`Mikroprozessortechnik`
.. |rfe|                            replace:: :term:`rfe`
.. |Radio-Fernsehen-Elektronik|     replace:: :term:`Radio-Fernsehen-Elektronik`


.. Operating Systems:

.. |BDOS|            replace:: :term:`BDOS`
.. |BIOS|            replace:: :term:`BIOS`
.. |CCP|             replace:: :term:`CCP`
.. |CP/A|            replace:: :term:`CP/A`
.. |CP/M|            replace:: :term:`CP/M`
.. |CP/V|            replace:: :term:`CP/V`
.. |SCP|             replace:: :term:`SCP`
.. |V-Tape|          replace:: :term:`V-Tape`


.. Programming Languages:

.. |Assembler|       replace:: :term:`Assembler`
.. |Makroassembler|  replace:: :term:`Makroassembler`
.. |Disassembler|    replace:: :term:`Disassembler`
.. |Reassembler|     replace:: :term:`Reassembler`
.. |Debugger|        replace:: :term:`Debugger`
.. |Linker|          replace:: :term:`Linker`
.. |BASIC|           replace:: :term:`BASIC`
.. |Tiny-BASIC|      replace:: :term:`Tiny-BASIC`
.. |Fortran|         replace:: :term:`Fortran`
.. |Pascal|          replace:: :term:`Pascal`


.. Network:

.. |IFLS|            replace:: :term:`IFLS`
.. |IFSP|            replace:: :term:`IFSP`
.. |IFSR|            replace:: :term:`IFSR`
.. |IFSS|            replace:: :term:`IFSS`
.. |RS232C|          replace:: :term:`RS232C`
.. |V.24|            replace:: :term:`V.24`


.. Technologies:

.. |OpAmp|           replace:: :term:`OpAmp`
.. |OPV|             replace:: :term:`OPV`
.. |SOC|             replace:: :term:`SOC`
.. |EMR|             replace:: :term:`EMR`
.. |CPU|             replace:: :term:`CPU`
.. |ZVE|             replace:: :term:`ZVE`
.. |PIO|             replace:: :term:`PIO`
.. |SIO|             replace:: :term:`SIO`
.. |DART|            replace:: :term:`DART`
.. |CTC|             replace:: :term:`CTC`
.. |DMA|             replace:: :term:`DMA`
.. |NMI|             replace:: :term:`NMI`
.. |RAM|             replace:: :term:`RAM`
.. |DRAM|            replace:: :term:`DRAM`
.. |SRAM|            replace:: :term:`SRAM`
.. |ROM|             replace:: :term:`ROM`
.. |PROM|            replace:: :term:`PROM`
.. |EPROM|           replace:: :term:`EPROM`
.. |EEPROM|          replace:: :term:`EEPROM`
.. |AD|              replace:: :term:`AD`
.. |DA|              replace:: :term:`DA`
.. |OSS|             replace:: :term:`OSS`
.. |BAS|             replace:: :term:`BAS`
.. |BSA|             replace:: :term:`BSA`
.. |BWS|             replace:: :term:`BWS`
.. |KMBG|            replace:: :term:`KMBG`
.. |RGB|             replace:: :term:`RGB`

.. Abbreviations:

.. |Vpp|             replace:: :term:`Vpp`

.. Local variables:
   coding: utf-8
   mode: text
   mode: rst
   End:
   vim: fileencoding=utf-8 filetype=rst :
